CXX = clang++

C++17 =
ifeq ($(CXX),clang++)
	C++17=--std=c++1z
else
	C++17=--std=c++17
endif

CPPFLAGS = -I include -I src -I src/sagl
CFLAGS = -g -Wall
CXXFLAGS = -g -Wall $(C++17)

vpath main.cpp src

bin/sagl:	main.cpp $(shell find include -name "*.hpp")
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -o $@ $<

.PHONY:	clean
clean:
	-rm -f bin/sagl

example:	bin/sagl
	./bin/sagl
